### ISSUE TITLE
Atmospheric pressure comparison for error detection

### ISSUE THREAD

**Issue by Sirvine1994** [HorizonsRC/hydrobot#2]
Atmospheric pressure does not vary a lot across the region, so nearby sites can be used for error detection.

After any spike removal and normalizing to a consistent altitude, we can compare the atmospheric data for the nearest site or a group of nearby sites. In cases where the data has a very good correlation, we can be reasonably sure that the atmospheric data is reading somewhat accurately, and the data can be automatically processed. Any sites which have poor correlation can be highlighted for human examination.

**Comment by nicmostert** [comment]
Related to a more general issue: #47

**Comment by Sirvine1994** [comment]
closed because duplicate
