### ISSUE TITLE
Support for multiple source files.

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#43]
In some cases, data might need to be pulled from multiple source files for a complete processing run. Might need to get them from archives and raw automation sources.

I think it would make sense to build a source file hierarchy into hydrobot so that it can search multiple files to get all the data it needs for any particular datetime range. However, passing a list of source files to be searched in order is probably a good start.

**Comment by nicmostert** [comment]
I'm beginning to think this is more of a beta release thing. At this point it is possible and relatively easy to obtain data from another source and adding it to our source. I'll do some testing and get back to this.

**Comment by nicmostert** [comment]
Moving this to beta release.

**Comment by Sirvine1994** [comment]
We do this now
