### ISSUE TITLE
More comprehensive gap visualisation.

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#46]
At present it is hard to distinguish the types of gaps. In practice we have many different types of gaps, and they should be displayed in different ways to distinguish them more clearly. Here are some types I can think of right now, but there may be more:

- Missing data (There is no timestamp for this point, it doesn't exist)
- NaNs (There is a timestamp, but the data is a NaN or None of some sort)
- Small gaps (Gaps that are small enough to close without needing to fill with synthetic data)
- Large gaps (Gaps that are large enough to justify replacement using synthetic data)

For the same reason, it makes sense to support the plotting of synthetic data in a clear and comprehensive way. Perhaps in a different "view" or plot, showing which infill method was used.

**Comment by nicmostert** [comment]
This is not strictly necessary for the Stable Hybrid Processing Workflow Milestone, but it would make things a lot easier.

**Comment by nicmostert** [comment]
Yeah I'm removing this from the milestone due to time constraints. Also, sam pointed out that these gaps are actually visually distinct in our current visualizer. This now falls into a visualizer enhancement category. I'll leave this open in case I want to write a "gap viewer" that marks them with big obvious bars at some point.

**Comment by Sirvine1994** [comment]
I think we've moved on from this
