### ISSUE TITLE
Measurement-specific Processor

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#56]
Measurements will end up requiring some very specific handling and processing. E.g a when processing water level, we would need to store the concept of a neighbouring WL (#47) site, but also be aware of important rainfall sites up the catchment. We would also care about the rainfall peaks at those rainfall sites, the lag times from the rainfall sites to the WL site, etc (#48).

I think this should be handled through inheritance. That way we can have a WaterLevelProcessor object that has a concept of rising and falling limbs (#48), master base flow (#49), etc, and can also create RainfallProcessor objects when required to find rainfall peaks that we can use to provide information for WL gap filling etc.

**Comment by nicmostert** [comment]
We started this action by making a DOProcessor (#111). While doing this I realised that this also ties into #47 and #43 because some measurements like DO needs auxiliary measurements to QC encoding and other processing steps.

**Comment by Sirvine1994** [comment]
This is done for rainfall and DO, will add for other data sources as needed
