### ISSUE TITLE
Get check data into hilltop faster and/or easier.

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#73]
Patch. At present the check data does not go into hilltop with the xml file. The other way is to copy and paste it from some excel file somewhere into hilltop, or to upload it using the Sorren Warren Script. We should figure out the fastest way, and streamline it by making sure we generate a csv in the correct format for the script or to be copy/pasted.

**Comment by Sirvine1994** [comment]
Workaround: using the output from the R script and copy pasting into the processed hts file. Future work should get the check data to come with the xml import

**Comment by nicmostert** [comment]
Done, check data goes directly into xml now. 0.6.0
