### ISSUE TITLE
Visual bugs in comments table

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#75]
There are some weird visual glitches in the comments table when using the diagnostic dash. Sometimes text is misplaced, sometimes there are just blank cells. Hitting the home button sometimes fixes this. This is especially prevalent when using a narrower screen size. Probably a known plotly issue, should check it out.

![image](https://github.com/HorizonsRC/hydrobot/assets/142271462/ed08e752-9dc2-432d-8790-179284cb98d7)

**Comment by Sirvine1994** [comment]
Blank lines seem to be caused by newlines - might need to escape these

**Comment by Sirvine1994** [comment]
Might also be due to overly long comments with no newlines?
