### ISSUE TITLE
Out of validation range needs an adjustable default value

### ISSUE THREAD

**Issue by Sirvine1994** [HorizonsRC/hydrobot#85]
Out of validation range is semi-hard-coded as 2 months and qc 200. These should be adjustable for different processing runs and/or measurements.

Will need to take that info from the config.yaml and input this into evaluator.downgrade_out_of_validation() and evaluator.quality_encoder(), and whereever these functions are used in processor.

**Comment by nicmostert** [comment]
Completed in 0.6.0
